import type { User, Product, Customer } from './types'
import { generateId } from './constants'


export const seedProducts: Product[] = [
  // Pig Feeds
  {
    id: generateId(),
    name: 'Hog Grower Feeds',
    category: 'feeds',
    retailPrice: 1350,
    wholesalePrice: 1250,
    capitalPrice: 1100,
    stock: 50,
    unit: 'sack',
    lowStockThreshold: 10,
    isApproved: true,
    createdBy: 'admin',
    approvedBy: 'admin',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Hog Finisher Feeds',
    category: 'feeds',
    retailPrice: 1400,
    wholesalePrice: 1300,
    capitalPrice: 1150,
    stock: 45,
    unit: 'sack',
    lowStockThreshold: 10,
    isApproved: true,
    createdBy: 'admin',
    approvedBy: 'admin',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Piglet Starter Feeds',
    category: 'feeds',
    retailPrice: 1500,
    wholesalePrice: 1400,
    capitalPrice: 1250,
    stock: 30,
    unit: 'sack',
    lowStockThreshold: 8,
    isApproved: true,
    createdBy: 'admin',
    approvedBy: 'admin',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Sow and Weaner Feeds',
    category: 'feeds',
    retailPrice: 1450,
    wholesalePrice: 1350,
    capitalPrice: 1200,
    stock: 35,
    unit: 'sack',
    lowStockThreshold: 10,
    isApproved: true,
    createdBy: 'admin',
    approvedBy: 'admin',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Hog Fattener Feeds',
    category: 'feeds',
    retailPrice: 1380,
    wholesalePrice: 1280,
    capitalPrice: 1130,
    stock: 40,
    unit: 'sack',
    lowStockThreshold: 10,
    isApproved: true,
    createdBy: 'admin',
    approvedBy: 'admin',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Rice
  {
    id: generateId(),
    name: 'Sinandomeng Rice',
    category: 'rice',
    retailPrice: 55,
    wholesalePrice: 2200,
    capitalPrice: 2000,
    stock: 40,
    unit: 'kg',
    lowStockThreshold: 50,
    isApproved: true,
    createdBy: 'admin',
    approvedBy: 'admin',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Jasmine Rice',
    category: 'rice',
    retailPrice: 62,
    wholesalePrice: 2500,
    capitalPrice: 2300,
    stock: 35,
    unit: 'kg',
    lowStockThreshold: 50,
    isApproved: true,
    createdBy: 'admin',
    approvedBy: 'admin',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Dinorado Rice',
    category: 'rice',
    retailPrice: 70,
    wholesalePrice: 2800,
    capitalPrice: 2600,
    stock: 25,
    unit: 'kg',
    lowStockThreshold: 30,
    isApproved: true,
    createdBy: 'admin',
    approvedBy: 'admin',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'NFA Rice',
    category: 'rice',
    retailPrice: 45,
    wholesalePrice: 1800,
    capitalPrice: 1650,
    stock: 60,
    unit: 'kg',
    lowStockThreshold: 100,
    isApproved: true,
    createdBy: 'admin',
    approvedBy: 'admin',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Red Rice',
    category: 'rice',
    retailPrice: 80,
    wholesalePrice: 3200,
    capitalPrice: 3000,
    stock: 15,
    unit: 'kg',
    lowStockThreshold: 20,
    isApproved: true,
    createdBy: 'admin',
    approvedBy: 'admin',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const seedCustomers: Customer[] = [
  {
    id: generateId(),
    name: 'Maria Santos',
    phone: '0918-234-5678',
    address: 'Purok 1, Brgy. San Jose',
    creditBalance: 2500,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Pedro Reyes',
    phone: '0927-345-6789',
    address: 'Purok 3, Brgy. Centro',
    creditBalance: 5000,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Jose Garcia',
    phone: '0935-456-7890',
    address: 'Sitio Maligaya, Brgy. Norte',
    creditBalance: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Ana Mendoza',
    phone: '0917-567-8901',
    address: 'Purok 5, Brgy. Sur',
    creditBalance: 1500,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    name: 'Ricardo Cruz',
    phone: '0926-678-9012',
    address: 'Sitio Bagong Silang',
    creditBalance: 3500,
    createdAt: new Date().toISOString(),
  },
]
